---
name: Check for spelling with vale

on:
  pull_request:
    branches: [ main ]

jobs:
  vale:
    name: Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Vale
        uses: Consensys/github-actions/docs-spelling-check@spelling-on-changes
        with:
          FILEPATHS: "docs/**"
